import React from "react";

export const metadata = {
  title: "Form | Multi Step Form",
  description: "Generated by create next app",
};
export default function formLayout({ children }) {
  return <div>{children}</div>;
}
